Add parakeet on modal with clustering and sortformer diarization
For some reason, I couldn't make streaming_sortformer work with long
form audio without blowing up the GPU.

It gives me the following error.

torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 324.43 GiB. GPU 0 has a total capacity of 44.39 GiB of which 26.41 GiB is free. Process 1 has 17.97 GiB memory in use. Of the allocated memory 10.66 GiB is allocated by PyTorch, and 6.80 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

sortformer backend doesn't work on long form audio, so we have a guard
for audio > 120s to use clustering backend.